
# TODO: make this work with pnpm

name: CI
on: [push]
env:
  TZ: "America/New_York"
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Check Dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: .yarn/cache
          key: yarn-cache-${{ github.job }}
          restore-keys: yarn-cache-
      - name: Install Dependencies
        run: yarn install
      - name: Lint Source Files
        run: yarn run lint
      - name: Build Project
        run: yarn run build
      - name: Run Tests
        run: yarn run test
